### ISSUE TITLE
Hint system

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#1]
Systém hintů, který v dané místnosti zobrazí malou nápovědu. 
Příkaz POMOC.

**Comment by raguklemenso** [comment]
Pokud už shořel Kapitál:
Bohužel už ti shořela kniha, a proto budeš muset začít znovu od začátku pomocí hesla RESTART.
m1-m2: Bude třeba něco zapálit něco, co bude dlouho hořet. Pokud se to nepovede napoprvé, tak to nevzdávej!
m3: Najdeš tu něco, co ti dodá sílu.
m4: Zamysli se, proč tvé kroky duní.
m5: Seber, co vidíš, a neotálej!
m6: Zkus to tu pořádně prozkoumat.
m7: Seber, co vidíš!
m8: Do dveří bude třeba zadat čtyřmístný kód. Zkus si vzpomenout na důležité roky v dějinách Československa.
m9: Poklop bude třeba odemknout klíčem, který někdo někde pohodil.
m10: V míse není voda, takže to, co v ní najdeš, bude suché.
m12-m17: V tomhle městě ti mapa nepomůže. Zkus postupovat až tam, odkud už cesta nevede.
m18: Nedoporučuje se být přímým účastníkem výbuchu!
m20: Tady nic zajímavého nenajdeš.

**Comment by mkouba** [comment]
@raguklemenso Muzes do mistnosti pridat hinty po vzoru: https://github.com/mkouba/tae/blob/master/prestavba/prestavba.js#L601

**Comment by raguklemenso** [comment]
@mkouba Super, udělám.

**Comment by raguklemenso** [comment]
Hint pro failstate (shorela kniha):
Bohužel už ti shořela kniha, a proto budeš muset začít znovu od začátku pomocí hesla RESTART.
