### ISSUE TITLE
EN - stone that's flying toward you - missing alternative name

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#103]
v ČJ je správně toto:
![image](https://user-images.githubusercontent.com/52992266/83309364-5a343e00-a209-11ea-9457-ba52c541c9d2.png)

V EN se píše pouze stone. Chybí klíč na ten alternativní název.

**Comment by mkouba** [comment]
Ve skutecnosti byl problem v tom, ze dekorujeme jmeno 2x (neurcity clen a lokace).
