### ISSUE TITLE
Saving should not count as a turn

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#106]
Už jsme to myslím řešili - ukládání se bere jako tah a způsobuje na různých místech game over - tak by to nemělo být.

![image](https://user-images.githubusercontent.com/52992266/83354641-506e2000-a35a-11ea-901e-49638d16b78c.png)

**Comment by mkouba** [comment]
Tohle mame vyresene sice obecne, nicmene v nekterych lokacich mame jeste specialni `afterAction` logiku.
