### ISSUE TITLE
Saving/loading should not be possible across languages

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#107]
Jde nahrát CZ savegame v EN verzi a pak je část anglicky a část česky. Asi by savegames měly mít v sobě kód jazyka, aby se to nestávalo.

**Comment by mkouba** [comment]
Jen pro info - tohle se stava jen lokalne u nekterych prohlizecu (nejspis IE, na firefoxu ma kazda stranka svuj local storage).
