### ISSUE TITLE
M10 - cop doesn't change into corpse when killed

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#108]
Popis mrtvoly zůstává stejný i po zabití v CZ i EN ("Chystá se zmlátit tě"). Uniforma se generuje do nekonečna (viz issue #104,)

![image](https://user-images.githubusercontent.com/52992266/83360820-685a9980-a384-11ea-8aac-f5c699592172.png)
![image](https://user-images.githubusercontent.com/52992266/83360823-6db7e400-a384-11ea-9cfc-34b6e6439c8e.png)

**Comment by mkouba** [comment]
To by melo byt opraveme. @raguklemenso prosim muzes otestovat?
