### ISSUE TITLE
Stolen diamonds should trigger failstate

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#112]
Korektor upozornil ta to, že Indy nehlásí fail state při ukradení diamantů. Bude to třeba dodělat.
Po ukradení diamantů je třeba nastavit failstate na true.

**Comment by mkouba** [comment]
Bude to chtit nejaky text...

**Comment by raguklemenso** [comment]
CSS - styl hint:
"Bez diamantů hru nepůjde dohrát. Nahraj pozici příkazem LOAD nebo napiš RESTART a začni znovu."
"You won't be able to finish the game without the diamonds. LOAD a savegame or RESTART to try again."
