### ISSUE TITLE
Finetune DICTIONARY and ALIASES FOR

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#114]
- Je to užitečná funkce!
- Za výpis obojího bych dal tečku. (konec věty)
- Pokud nejsou žádné aliasy, text v Č: "žádné.", v AJ "none."
- Ve výpisu v Indym chybí speciální slovesa pro uniformu.

**Comment by mkouba** [comment]
> Je to užitečná funkce!

:-)

> Za výpis obojího bych dal tečku. (konec věty)

+1

> Pokud nejsou žádné aliasy, text v Č: "žádné.", v AJ "none."

Ok, byl jsem trochu liny ;-).

>  Ve výpisu v Indym chybí speciální slovesa pro uniformu.

Funguje to ted tak, ze se aliasy vypisuji jen pro akce, ktere ma uzivatel momentalne k dispozici. Tj. akce globalni + lokace + inventar. Jinak bychom museli pokazde prohledat vsechno, coz se mi uplne nelibi...
