### ISSUE TITLE
Add bug report email

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#117]
Bylo by dobré dát do legendy email, kam se dají posílat bug reporty. Asi by to šlo přes GitHub, ale nejsem si jistý, jestli to všichni uživatelé dokážou.

**Comment by mkouba** [comment]
Na github issues musis byt prihlaseny. Navrhuju pouzit google docs form?

**Comment by raguklemenso** [comment]
OK, udělám to!
