### ISSUE TITLE
I EN - request to use noun aliases to refer to objects ("cop" for "dead cop")

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#118]
Dostal jsem od americké testerky request, jestli by šlo místo "dead cop" a "dead policeman" psát jen "cop, policeman". Podle mě to teoreticky možné je, protože nemůže dojít k nejednoznačnosti - vždycky je tam buď objekt _cop1_ nebo _corpse1_ - nikdy oba dva najednou. Tak jsem přidal "cop" do aliasů _corpse1_, ale lokace přestala fungovat - cop1 jakoby neumírá.
Jsou tam ty případy čtyři a možná by bylo dobré to nějak zařídit. Už mě to napadlo předtím. V ČJ to podle mě problém není, protože logicky zkrátíš mrtvolu policajta na mrtvolu, ale v EN je "dead" adjektivum, takže dává smysl to vypustit.

**Comment by mkouba** [comment]
> Tak jsem přidal "cop" do aliasů corpse1, ale lokace přestala fungovat - cop1 jakoby neumírá.

Nefunguje to proto, ze kdyz se kontroluje, jestli je v lokaci `cop`, tak se prohledavaji i aliasy: https://github.com/primitivedesigns/remakes89/blob/master/indy/indy.js#L309. Vetsina vyhledavacich funkci tak funguje. Museli bychom to prepsat. Nevim, jak narocne by to bylo...

**Comment by mkouba** [comment]
Asi by to slo udelat tak, ze vsechny "interni" hledani budou ignorovat aliasy. Ale trochu se bojim bugu, ktere se objevi ;-).

**Comment by raguklemenso** [comment]
Já bych se za to určitě přimlouval a rád pak vše otestuju. Bylo by opravdu lepší, kdyby interní hledání ty aliasy ignorovalo.
