### ISSUE TITLE
I EN - uniform must be picked up before you use it

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#121]
Je možné obléct uniformu, aniž by ji člověk vzal. Objeví se správně hláška plného inventáře, ale uniformu pak stejně máš na sobě, takže se rozbije ten puzzle, kdy můžeš mít kromě uniformy jen jednu věc. Takže by se měla vypsat hláška, ale obléknutí by nemělo projít.

![image](https://user-images.githubusercontent.com/52992266/86465646-5fb60400-bd32-11ea-85bb-ea93e7e26220.png)

**Comment by mkouba** [comment]
Uf, to snad nikdy neskonci. Hm, podle te posledni hlasky to spis vypada, ze jen vypiseme zpravu. Ale ted tam vidim jinou chybu. Zkusim opravit.
