### ISSUE TITLE
P CZ - cancel failstate after examining altar

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#123]
V Přestavbě se po dohoření knihy nastaví failstate, což je dobře. Ale pokud už je člověk za temnou místností a má všechny potřebné předměty (zapalovač a dynamit), mohli bychom klidně ten failstate zase zrušit - už není třeba člověka upozorňovat, že kniha shořela. Snažil jsem se to vyřešit na řádku 203 v prestavba.js, ale asi jsem to udělal špatně.

**Comment by mkouba** [comment]
`setFailState()` nelze takhle pouzit. Proc zrovna na radku 203?

**Comment by raguklemenso** [comment]
Protože při prozkoumání oltáře už je jasné, že se hráč dostal za temnou chodbu, a že hra tedy půjde dohrát.
