### ISSUE TITLE
ZAP KNI (zapal knihu) executes Z (West) instead of ZAPAL KNIHU

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#18]

**Comment by mkouba** [comment]
Problem je, ze tam jsou ve skutecnosti 2 akce, ktere odpovidaji `ZAP`: `zapal` a `zapad`. Puvodni verze hry zadny takovy konflikt nema. @raguklemenso Co udelame? Momentalne se vezme prvni odpovidajici akce. Muzeme vypsat dostupne prikazy, tj. neco jako "Dostupne prikazy: zapal, zapad".

**Comment by raguklemenso** [comment]
Asi jo. Ale "zapad" nemá nikdy objekt, takže pokud tam je objekt, tak to musí být "zapal"

**Comment by mkouba** [comment]
To uz bys chtel moc :-). Akce se hledaji jen podle jmena, tzn. prvniho slova. Zbytecne bychom asi komplikovali uz tak zamotany kod.
