### ISSUE TITLE
Interruptions of title screen

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#20]
Pokud mačkneš enter příliš rychle při výpisu úvodní obrazovky (ne obrázku, ale toho potom), tak se pak část vypíše na herní obrazovku. 

![image](https://user-images.githubusercontent.com/52992266/64617596-0a91b600-d3df-11e9-9302-a4a99519eaca.png)

**Comment by mkouba** [comment]
To uz je opravene. Prosim test.

**Comment by raguklemenso** [comment]
Jo, už to jde!
