### ISSUE TITLE
Darkness indicator not working

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#21]
Podařilo se mi dostat do stavu, kdy mi dohořel Kapitál, byla tma a chodil jsem po místnostech, kde má být tma. Ale vypsal se vždycky jejich popis, pak až to zmizelo a objevilo se "Je tu tma."

**Comment by mkouba** [comment]
Zatracene efekty ;-). Je to proto, ze my tmu implementujeme tak, ze smazeme puvodni info. Jenze kvuli efektu to chvilku trva... Nejak to upravim.
