### ISSUE TITLE
Announce new objects

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#23]
V původní verzi se po prozkoumání, které vygeneruje nové předměty (onExamine) vypíše zpráva, že předmět vidíš - viz screenshot. (Vidis sekeru.)

![image](https://user-images.githubusercontent.com/52992266/66005123-d2940500-e4aa-11e9-8943-c6bf9aff486e.png)

**Comment by mkouba** [comment]
Hm, nedavalo by vetsi smysl vypsat vsechny predmety, ktere vidis?
