### ISSUE TITLE
Make evasion of game over impossible

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#24]
Game overu v místnosti 1 se nyní dá utéct pohybem do jiné místnosti (P). V původní hře se i to počítá jako tah a nastane game over.

**Comment by mkouba** [comment]
OK. Mne to prislo jako rozumna vec umoznit utek. Ale tady bychom asi meli zachovat puvodni chovani.

**Comment by raguklemenso** [comment]
Jo, mechaniky bych nechal jako v originálu, i když jsou kruté 😊

Jaroslav Švelch, Ph.D.
New media and digital games scholar
Assistant professor, Faculty of Social Sciences, Charles University, Prague
Postdoctoral fellow (2017-2019), Games and Transgressive Aesthetics project, University of Bergen: http://gta.b.uib.no/
________________________________________________________
My book GAMING THE IRON CURTAIN: How Teenagers and Amateurs in Communist Czechoslovakia Claimed the Medium of Computer Games
Out now on MIT Press, http://ironcurtain.svelch.com

@raguklemenso
Phone: +420 773 988 425
