### ISSUE TITLE
Destroy axe item after killing cop

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#25]
po použití sekery sekera mizí (je zaseknutá v hlavě)

**Comment by mkouba** [comment]
Aha, to me nenapadlo. Myslel jsem, ze ji po pouziti z hlavy hrdina vytahne ;-).

**Comment by mkouba** [comment]
Musim cist ty popisky poradne...

**Comment by raguklemenso** [comment]
No, to je moje chyba, nenapsal jsem to do contentu...
