### ISSUE TITLE
Adjust generic messages (exits, object indication)

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#26]
V originále se některé věci vypisují trochu jinak. Např. každý předmět má svou vlastní větu (k diskusi, zda to zachovat). Pokud je východ možný na všechny směry kromě jednoho, tak se vypíše "můžeš kamkoli jen ne x" (také k diskusi, jsem spíš pro to to zachovat.)

Porovnání:
![image](https://user-images.githubusercontent.com/52992266/66005861-ff491c00-e4ac-11e9-93ca-2e5df1c9644c.png)

![image](https://user-images.githubusercontent.com/52992266/66005871-06702a00-e4ad-11e9-993c-fafd5caf72e8.png)

**Comment by raguklemenso** [comment]
Ještě by možná bylo dobré v tom výpisu dát před poslední objekt spojku "a"

**Comment by mkouba** [comment]
> Pokud je východ možný na všechny směry kromě jednoho, tak se vypíše "můžeš kamkoli jen ne x...

To mi neprijde moc uzitecne. Jako uzivatel bych se musel zamyslet, co to znamena kamkoliv...

> Např. každý předmět má svou vlastní větu

Potom nedava smysl https://github.com/mkouba/tae/issues/26#issuecomment-537266625 - pridat spojku, nebo?

**Comment by raguklemenso** [comment]
OK, taky se přikláním k tomu přidat spojku a nechat vypsat všechny směry.

Jaroslav Švelch, Ph.D.
New media and digital games scholar
Assistant professor, Faculty of Social Sciences, Charles University, Prague
Postdoctoral fellow (2017-2019), Games and Transgressive Aesthetics project, University of Bergen: http://gta.b.uib.no/
________________________________________________________
My book GAMING THE IRON CURTAIN: How Teenagers and Amateurs in Communist Czechoslovakia Claimed the Medium of Computer Games
Out now on MIT Press, http://ironcurtain.svelch.com

@raguklemenso
Phone: +420 773 988 425
