### ISSUE TITLE
No LOAD of savegames from another game

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#30]
Dá se loadnout pozice z jiné hry (v Indym z Přestavby) -> chaos

**Comment by mkouba** [comment]
To by jit nemelo, protoze localStorage se vaze na konkretni stranku. Nicmene neuskodi, kdyz tam pridame prefix pro kazdou hru. Tj. standardni nazev pozice pro Indyho bude `indy_save`.

**Comment by raguklemenso** [comment]
Zvláštní, mně se to fakt povedlo 😊

Jaroslav Švelch, Ph.D.
New media and digital games scholar
Assistant professor, Faculty of Social Sciences, Charles University, Prague
Postdoctoral fellow (2017-2019), Games and Transgressive Aesthetics project, University of Bergen: http://gta.b.uib.no/
________________________________________________________
My book GAMING THE IRON CURTAIN: How Teenagers and Amateurs in Communist Czechoslovakia Claimed the Medium of Computer Games
Out now on MIT Press, http://ironcurtain.svelch.com

@raguklemenso
Phone: +420 773 988 425
