### ISSUE TITLE
No error message on using items under wrong conditions

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#35]
Předměty, které v dané chvíli nesplňují podmínky použití (ale dají se použít jindy a jinde), nevyvolají chybovou hlášku

Např.:
Pokud v M5 použiješ štít potom, co už byl odražený kámen, tak se nevypisuje žádná zpráva. Stejně tak se nevypíše nic, pokud dáš použij slovník.

**Comment by raguklemenso** [comment]
Ověřeno na dalších příkladech - je to tak (předměty, které v dané chvíli nesplňují podmínky použití nevyvolají chybovou hlášku)

**Comment by mkouba** [comment]
Jaka chybova hlaska se ma vypsat? Jak je to v originalu?

**Comment by raguklemenso** [comment]
Běžná hláška "To bohužel nejde!!!"

**Comment by raguklemenso** [comment]
Toto se stávalo často a lidi to mátlo. Např. při použití štítu ve špatné lokaci se nevypíše žádná chybová hláška.

**Comment by mkouba** [comment]
Prosim otestovat.
