### ISSUE TITLE
Fix uniform switch

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#36]
Jakmile jednou použiješ uniformu, zůstane oblečená, i když ji položíš. 
Uniformu nejde svléct.
Nefungují zatím příkazy svleč/obleč
Jsem pro to, aby se uniforma dala svlékat/oblékat příkazem použij uniformu - a pak popřípadě speciálními příkazy svleč/obleč

**Comment by mkouba** [comment]
Potvrzuji, ze "poloz uniformu" nezmenilo stav uniformy = bug a ze "pouzij uniformu" pouze oblekalo. Ostatni sice melo fungovat, ale mohlo to byt rozbite kvuli temto bugum. Upravil jsem to tak, ze:
"pouzij uniformu" obleka/svleka uniformu (pokud uniforma neni v inventari, tak se ji nejprve pokusi vzit). "poloz uniformu" ji svlekne a polozi. Pridal jsem test, ale bylo by dobre to overit.
