### ISSUE TITLE
Civilian does not kill you

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#37]
v m15 se nespouští game over pokud máš uniformu. ("Vrhnul se na tebe civilní občan pod dojmem, že jsi člen VB. Máš totiž ještě oblečenou uniformu.")

**Comment by mkouba** [comment]
Hm, tohle by melo fungovat - pridal jsem automatizovany test. Mohl bys to prosim pretestovat? Je mozne, ze to melo souvislost s #36.
