### ISSUE TITLE
Fix m16 mechanics

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#41]
v m16 je několik zádrhelů:

1. příslušník tě má zmlátit (gameover) po jednom tahu, nyní to je po dvou.
2. když položíš diamanty, příslušník má ihned zmizet a má se vypsat zpráva (správně pochopil...) Nyní se zpráva vypíše až v dalším tahu.
3. zpráva o příslušníkově odchodu se opakuje každý další tah.
4. Po položení diamantů má zmizet příslušník - nyní se odstraní gameover, ale příslušník zůstane přítomný

**Comment by mkouba** [comment]
Prosim o pretestovani. Pokud OK, tak zavrit.
