### ISSUE TITLE
Replace inventory message

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#44]
Vložit hlášku z originálu: Pokud máš věci tak, to je : "Máš u sebe věc1, věc2 a víc už ani >p<." Moc nechápu, co to znamená (asi prd), ale měli bychom to zachovat.
Pokud nemáš nic, tak se vypíše "Máš u sebe hovno a víc už ani >p<." To moc nedává smysl, tak bych místo toho dal "Máš u sebe hovno."

**Comment by mkouba** [comment]
Prosim overit.
