### ISSUE TITLE
fix messages on full inventory

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#50]
Pokud chceš vzít třetí věc, napíšou se dvě hlášky.

![image](https://user-images.githubusercontent.com/52992266/66646523-ab65d200-ec26-11e9-9f90-ecea1f544f2e.png)

Navrhuju druhou nepsat a nahradit první něčím víc srozumitelným - můj návrh: "Víc už toho neuneseš!"

**Comment by mkouba** [comment]
Prosim overit.
