### ISSUE TITLE
Display hints before gameover

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#53]
V Indym v místnostech jako M1 máš prostor dát jeden příkaz. Správně tě to po jednom chybném zabije. Ale měli bychom dát možnost vypsat hint na příkaz POMOC - poté by měla následovat smrt.

**Comment by mkouba** [comment]
Uf, dalsi vyhybka. Ale mas pravdu, ze jinak nemas sanci ten hint zobrazit. Nicmene bych to udelal mozna jinak. Co takhle automaticky vypsat hint (az pod "ZPRÁVA Z AMERICKÉHO TISKU..."), pokud umres a mistnost ma nejaky hint definovany?

**Comment by raguklemenso** [comment]
To bych nedělal kvůli lidem, kteří chtějí "original experience" bez hintů...

**Comment by mkouba** [comment]
To moc nechapu. IMHO bude dost matouci, ze vsechny prikazy povedou k "ciste" smrti a POMOC ti neco vypise, jeste nez umres...

**Comment by raguklemenso** [comment]
podle mě (a i to tak je v originálu) by se měl jakýkoli příkaz, který zadáš, vyhodnotit. Tj. v m1 "prozkoumej fízla" vypíše popis fízla. Nebo SAVE uloží hru, POMOC vypíše hint, SLOVNIK vypíše slovník. A ihned pak, pokud jsi nezadal správný příkaz, tak se ukáže game over. Teď se ten příkaz nevyhodnotí, což je podle mě chyba.
