### ISSUE TITLE
Add/fix aliases

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#57]
Věci, které lidi často zkoušeli psát a nefungovaly:

"pouzit" = použij, nyní nefunguje
"vem" = "vezmi"
"zahoď, zah, zahod, zahodit" = polož
"jdi dolů" = dolů atd.

**Comment by mkouba** [comment]
"jdi dolů" bude trochu orisek, protoze budeme muset nejak posbirat aliasy pro vystupy z lokace (momentalne by fungovalo narp. pouze "jdi S" nebo "jdi dolů", ale uz ne "jdi sever" nebo "jdi dolu").

**Comment by raguklemenso** [comment]
Nemůžeme prostě "jdi" a "jdi na" jakoby vymazat z toho vstupu? tj. "jdi dolů" => "dolů", "jdi na sever" => "sever"
Je to asi dementní řešení, ale podle mě nejjednodušší

**Comment by raguklemenso** [comment]
nebo že D by mělo alias "jdi dolů" - nevím ale jestli alias může mít v sobě mezeru

**Comment by mkouba** [comment]
> Nemůžeme prostě...

Ano, muzeme. Ano, je to dementni, ale skoro bych to tak udelal.

> nebo že D by mělo alias "jdi dolů"

To zatim nejde. Kazda akce/prikaz je jedno slovo a pak jsou parametry. Takze bychom museli mit akci "jdi" a pak nejak ziskat odpovidajici nazev vychodu.

**Comment by mkouba** [comment]
Muzes overit. Nefunguje to pro `autocomplete`, ale s tim asi muzeme zit ;-).
