### ISSUE TITLE
Easier saving/loading 

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#59]
1. Lidi zapomínají názvy pozic. Měla by být možnost je vyvolat.
Můj návrh: změnit funkci LOAD bez argumentu - vypíše se instrukce "Zadej příkaz LOAD a za něj z následujících pozic:" a seznam pozic.
SAVE bez argumentu nadále dělá totéž. Ale lidi to nepoužívali. Bez výjimky dávali pozicím název.

2. Lidé si stěžovali, že se musí po smrti v Indym proklikat přes všechny úvodní obrazovky. Asi bych jim to zjednodušil. Je to k diskusi, navrhuju 2 varianty:
a) přidat k R-Restart možnost L-Load poslední pozice (podle timestamp) (preferuje náš zadavatel/kurátor)
b) po Restartu přeskočit úvodní obrazovky. Přidat možnost Intro (I) - restart i s úvodem. Tím by se ty prokliky zredukovali a pak mohl člověk rovnou loadovat.

3. Pokud se za LOAD zadá špatné jméno pozice, nevyhodí to chybu, ale tváří se to, že se pozice nahrála -> lidé jsou zmatení.

**Comment by mkouba** [comment]
ad 1. Muzeme mit taky samostatny prikaz pro vypis pozic. Nicmene, vzhledem k tomu, ze pocet pozic neni omezeny, muze byt seznam dost dlouhy. Momentalne to fungovalo opet pres TAB, ktery doplnoval nazvy pozic (teda fungovalo to, ale pak se diky prefixu objevil bug, ktery jsem uz opravil).

ad 2. Moc se mi libi napad s nahranim posledni pozice.

ad 3. To opravim.

**Comment by mkouba** [comment]
Problem 3. opraven.

**Comment by mkouba** [comment]
ad 1. - pridal jsem akci "pozice", ktera zobrazi vsechny ulozene pozice.
ad 2. - varianta a) by mela fungovat.

**Comment by raguklemenso** [comment]
1. Stejně bych pro LOAD bez argumentu nechal vypsat pozice.
2. Chybová hláška po nahrání neexistující pozice má chybu, jsou tam dvě dvojtečky: "Nelze nahrát pozici: : NAZEV"

**Comment by mkouba** [comment]
Melo by byt opravene. Prosim overit.

**Comment by raguklemenso** [comment]
Pokud není žádná pozice, ukáže se toto:

![image](https://user-images.githubusercontent.com/52992266/68029008-94128580-fcb6-11e9-9868-9250a6e96cd2.png)

Bylo by lepší napsat něco jako žádná pozice.

**Comment by mkouba** [comment]
Melo by to ted psat `Uložené pozice: `. Bez carky. Mozna nejaky bug v implementaci [Array.prototype.join()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) v prohlizeci. Ale specialni zprava bude jiste lepsi... kolik takovych "corner cases" jeste budeme muset osetrit? ;-)

**Comment by raguklemenso** [comment]
Super! JInak se ještě může stát, že bude pozic přehnaně moc. Možná můžeme vypsat jen cca 20 posledních, jinak to může nějak odrolovat obrazovku nebo něco. 
Pro 0 pozic bych napsal "Nemáš žádnou uloženou pozici." stylem hint

**Comment by mkouba** [comment]
> Možná můžeme vypsat jen cca 20 posledních, jinak to může nějak odrolovat obrazovku nebo něco.

+1

> stylem hint

Mozna bychom meli stylem "hint" psat vsechny zpravy load/save?

**Comment by raguklemenso** [comment]
ano prosím, systémové zprávy týkající se pozic bych tak psal

**Comment by mkouba** [comment]
Melo by to byt.
