### ISSUE TITLE
P - fix dynamite

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#62]
1. povolit zapálení dynamitu jen pokud je položený v m17
V původní verzi nejde zapálit dynamit pokud není položený v m17 - zabraňuje to dalšímu fail statu - člověk nemůže přijít o dynamit před tím, než ho má skutečně použít. Nejde zapálit, ani když je v inventáři (tj. ne položený)
Navrhuju to udělat stejně jako v originále ALE při použití "zapal dynamit" v jiné místnosti dát vlastní chybovou hlášku (ve stylu CSS hint): "Nemáš důvod tady zapálit dynamit." Pokud bychom dali tu standardní, tak si pak lidi budou myslet, že dynamit nejde zapálit vůbec.
V M17 bych to udělal následovně: 
- stejně jako v originálě povolit zapálení položeného dynamitu
- pokud člověk zapálí dynamit v inventáři, tak se automaticky položí
- dynamit se změní na non-takeable

2. Nefunguje game over s explozí - jen se začerní obrazovka. Má se vypsat text: "Obrovská exploze otřásla městem, což jsi včak jako její přímý účastník neslyšel." A Gameover

**Comment by mkouba** [comment]
1. Hm, sice chapu, ze chces, aby to bylo jako original, ale tohle nedava moc smysl. To, ze zapalis dynamit v inventari a odneses si ho s sebou mi prijde jako vtipny konec hry (sam jsem to nekolikrat udelal). V puvodni verzi hry to byl spis bug. Ale muzeme jeste prodiskutovat.
2. Proverim a opravim.

**Comment by mkouba** [comment]
Problem 2 opraven.

**Comment by mkouba** [comment]
@raguklemenso Ma to byt "m18", ze?

**Comment by mkouba** [comment]
Prosim otestovat.
