### ISSUE TITLE
Fix burned book hint 

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#63]
Hint po shoření knihy by se neměl objevit automaticky, ale měl by se přidat k jakémukoli dalšímu hintu z dané místnosti. (Původně jsem si myslel, že by měl všechny ostatní hinty nahradit a navést tak hráče k restartu, ale pak mě testeři překvapili tím, že dokázali v tmavých místnostech všechno dělat po paměti. Takže shoření knihy nemusí nutně znamenat, že se hra nedá dohrát. Taky jsem podle toho upravil text hintu, ale nechal jsem ho místě, kde je teď.)

**Comment by mkouba** [comment]
S tim uplne nesouhlasim. Podle me by se mel zobrazit automaticky, tj. ve chvili, kdy kniha shori.

**Comment by mkouba** [comment]
Prosim otestovat...
