### ISSUE TITLE
L - text overflows into border

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#69]
![image](https://user-images.githubusercontent.com/52992266/68337939-cb7f9880-00e1-11ea-8eec-c4d8f2128c4b.png)

**Comment by mkouba** [comment]
To bude trochu orisek. Nevim proc, ale obcas to ten text spatne lame (vidi vetu jako cele slovo). Mozna je to kvuli tomu efektu. Musim proverit.

**Comment by raguklemenso** [comment]
Zvláštní, dělaly mi to i některé texty popisů místností, tak jsem tam vymazal všechny mezery a manuálně je znovu napsal a pak to šlo. jako kdyby tam bylo chybné kódování a některé mezery nebyly skutečně mezery. Možná to je taky problém prohlížeče.

**Comment by mkouba** [comment]
Koukal jsem. Byla tam zrejme pouzita nejaka nestandardni mezera, tipoval bych U+00A0, ktery se preklada jako non-breaking space, cili `&nbsp;`.

**Comment by mkouba** [comment]
Jo, je jich tam hodne! Nejspis to vzniklo diky CTRL+C primo z onedrive editoru. Opravim.
