### ISSUE TITLE
L - messages appear in wrong order

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#70]
Originál: 
![image](https://user-images.githubusercontent.com/52992266/68339474-f0c1d600-00e4-11ea-9289-e091d3a6a2a6.png)

Konverze:
![image](https://user-images.githubusercontent.com/52992266/68339497-fddec500-00e4-11ea-9368-29f3ac4132c9.png)

**Comment by mkouba** [comment]
Myslim, ze bychom mohli "Pouzil jsi zebrik" uplne vynechat. A napsat pouze "O.K. Pristavil jsi...". Co myslis?

**Comment by raguklemenso** [comment]
Určitě to je možné řešení, pokud by to bylo zbytečně složité přehodit.

**Comment by raguklemenso** [comment]
Totéž u použití dalších předmětů:
![image](https://user-images.githubusercontent.com/52992266/68433509-fdaefa00-01b6-11ea-9d1a-b978d58e649b.png)

**Comment by mkouba** [comment]
Zatim jsem dal tu obecnou hlasku pryc. Muzeme predelat.

**Comment by raguklemenso** [comment]
Duplicitní hláška i zde: 
![image](https://user-images.githubusercontent.com/52992266/68676239-df038700-0559-11ea-8091-58091fcaaf30.png)
