### ISSUE TITLE
L - remove ladder from inventory after using it in m16

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#72]
Po užití žebříku v m16 musí zmizet z inventáře.
Pak také platí, že pokud ho znovu vezmeš, tak zmizí průchod nahoru do m21.

**Comment by raguklemenso** [comment]
Také se po opakovaném použití žebříku generují další totožné východy:
![image](https://user-images.githubusercontent.com/52992266/68342166-4cdb2900-00ea-11ea-9ca1-f2d4cd86b014.png)

**Comment by mkouba** [comment]
Zebrik nemuze zmizet, ale polozime ho v mistnosti.

**Comment by mkouba** [comment]
Prosim overit.
