### ISSUE TITLE
L - wrong use of ladder game over not working properly

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#75]
Nezobrazuje se správný game over při použití žebříku ve špatné místnosti: 
![image](https://user-images.githubusercontent.com/52992266/68341862-a5f68d00-00e9-11ea-8afe-8ea20850e38d.png)

**Comment by mkouba** [comment]
Muzes to lepe popsat? Zkusil jsem upravit test a pouzil jsem zebrik v m10 a vidim spravnou zpravu i konec hry.

**Comment by raguklemenso** [comment]
Divný, u mně se ukáže chvíli nic, pak "Dlouho jsi nevydržel" a pak se to zastaví a musím refreshovat. Zpráva se neukazuje. Zkouším i na Chromu.

**Comment by mkouba** [comment]
Az budes mit chvili, tak to prosim otestuj.

**Comment by raguklemenso** [comment]
Funguje!
