### ISSUE TITLE
L - unable to examine box in m8

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#79]
Z nějakého důvodu se mi za určité podmínky nespouští examine bedny.
Zřejmě se to stává, když je odemčená.

**Comment by mkouba** [comment]
Co presne znamena "nespousti"? Nezobrazi se zadny popisek?

**Comment by raguklemenso** [comment]
Sorry za nepřesnost. Pokud je bedna otevřená, tak vůbec nejde vybrat ke zkoumání. Vypíše se jako jedna z možností, ale po zmáčknutí B se nic neděje.
![image](https://user-images.githubusercontent.com/52992266/68433934-09e78700-01b8-11ea-8213-ad74e32f2b8d.png)
