### ISSUE TITLE
L - add/fix wrong global actions

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#80]
Nefungují některé chytáky - použití předmětů v chybných místnostech. Např. hák, klíč

V případě kazety po chybné akci má zmizet z inventáře, ale nezmizí:

![image](https://user-images.githubusercontent.com/52992266/68343803-ee17ae80-00ed-11ea-9d94-3e1a877b7699.png)

**Comment by raguklemenso** [comment]
Nicméně hra jde dohrát i bez toho, takže můžeme být live ještě před tím, než se to dodá.

**Comment by mkouba** [comment]
Hm, ja myslim, ze kazeta by nemela zmizet. Je tam popisek znicene kazety. Nebo?

Hak opravim. Nejake dalsi veci?

**Comment by raguklemenso** [comment]
máš pravdu, nemá zmizet. ale hra už pak nejde dohrát.
Pak tam jsou ještě ty pitomé globální akce jako vyhození klíčku a baterie nebo zničení háku.
Je to na konci souboru content.

**Comment by mkouba** [comment]
> Pak tam jsou ještě ty pitomé globální akce jako vyhození klíčku a baterie nebo zničení háku.

To by melo fungovat. Teda hak jdu teprve pushnout, ale klicky a baterie uz tam jsou. Teda mozna to nefunguje dobre, ale je to tam ;-).

**Comment by raguklemenso** [comment]
Hm, ten klíč a klíček mi nějak nejdou použít mimo správné místo - píše se "nevím k čemu".

**Comment by mkouba** [comment]
Mas pravdu, ten "klicek" se jen lame v m10 a "klic" to nema definovane.

**Comment by mkouba** [comment]
@raguklemenso Mohl bys to lokalne otestovat?

**Comment by raguklemenso** [comment]
Super, funguje, jen se tam opět objevují u klíčku hlášky ve špatném pořadí: 
![image](https://user-images.githubusercontent.com/52992266/68681046-f5621080-0562-11ea-9bf7-e0400598dbf1.png)

**Comment by mkouba** [comment]
To neni spatne poradi, chybi tam `return true`, ktere znamena, ze se vec pouzila.
