### ISSUE TITLE
L - messages when taking nontakeable items

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#84]
Moje chyba - nějak se to nedostalo do analýzy. Nejen bedna, ale všechny non-takeable items mají svoji chybovou hlášku, že je nemůžeš vzít. Takže to je systematičtější, než jsme si mysleli!

devře (m5) - "Bohužel, ale dveře jsou tak masivní, že bys je sotva otevřel."
bednu - máme
vrata (m10) - "Myslím, že bych je nevzal ,ani kdyby byly otevřené, natož když  jsou zamčené."
poklop (m21) - "Je tak těžký, že kdybych ho vysadil z pantu, tak by mě srazil ze žebříku."
poklop (m16) - "Je moc vysoko!"

**Comment by mkouba** [comment]
Prosim otestovat. Zvlast ten poklop, kvuli kteremu pribyly dalsi ify... :-(

**Comment by raguklemenso** [comment]
Ony ty předměty nešly vůbec vybrat, aby je člověk vzal, takže se hlášky neukazovaly. Přidal jsem je tedy k bedně do výjimek u definice slovesa "vzít". Teď už to funguje krásně. Jen zvaž, jestli tam chceš mít tolik vyjímek nebo jestli to chceš řešit jinak.
