### ISSUE TITLE
Engine, I, L - sjednotit failstate hint

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#88]
Nyní se v Indym objeví po výbuchu automatický hint. Udělal bych to ale jako v Přestavbě, kde se ten hint připojuje k běžnému hintu v místnosti.
Mohla by to být funkce pro každou ze tří her. Pokud hráč dosáhne failstatu, tak se vypíše kromě normálního hintu i speciální failstate hint.
Zároveň jsem v Indym objevil ještě jeden fail state - když ti ukradnou diamanty. Až se to pak celé opraví, tak přepíšu failstate hint, aby neodkazoval pouze k výbuchu, ale i k tomuhle.

**Comment by raguklemenso** [comment]
Korektor též upozornil ta to, že Indy nehlásí fail state při ukradení diamantů. Bude to třeba dodělat.

**Comment by mkouba** [comment]
> Korektor též upozornil ta to, že Indy nehlásí fail state při ukradení diamantů. Bude to třeba dodělat.

Vytvor prosim samostatnou issue...

**Comment by raguklemenso** [comment]
Hotovo.
Do bundlu by měly přijít generická zpráva o tom, že hru už nelze dohrát, která se připojí za hint:
"Přišel jsi o předmět, který je nutný k dohrání hry. Nahraj uloženou pozici příkazem LOAD nebo začni znovu příkazem RESTART."
"You've lost an item needed to complete the game. LOAD a savegame or RESTART to try again."
