### ISSUE TITLE
L - fix videocassette behavior

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#90]
1. Nemůžu přijít na to proč, ale hned při prvním zkoumání videokazety hned po sebrání je zničená. 
Měla by být na začátku nezničená.

2. Opětovným použitím se zase spraví. To by nemělo jít.

3. Po zničení by se měl nastavit failstate na true a nemělo by jít vložit kazetu do videokamery.

**Comment by mkouba** [comment]
To bylo spatne vyhodnoceni popisku. Failstate jsem opravil.
