### ISSUE TITLE
L - more user-friendly saving/loading

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#91]
Při ukládání by nepoužité pozice mohly být vypsány šedě, aby si hráč nepřepisoval existující pozice.
V menu Save/Load bych přidal něco jako Zpět v případě, že si to hráč rozmyslí.

**Comment by mkouba** [comment]
Te sede barvy si asi nikdo nevsimne. Muzeme pozit jinou barvu...

**Comment by mkouba** [comment]
@raguklemenso ^ ?

**Comment by raguklemenso** [comment]
Tak třeba #2d5986 ? (tmavě modrošedá)

**Comment by mkouba** [comment]
@raguklemenso Dal jsem tam tu modrou z trikolory. Muzes to lokalne otestovat? Jo a vybarvujeme to i pro Load, aby to davalo smysl.

**Comment by raguklemenso** [comment]
Super, funguje!

**Comment by raguklemenso** [comment]
Napsal jsem to i do nápovědy.
