### ISSUE TITLE
L - remove the line break in the command line

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#96]
Sorry, že jsem tě to donutil udělat, ale vede to k neblahým následkům v úzkých rozlišeních: 
![image](https://user-images.githubusercontent.com/52992266/68674270-d4df8980-0555-11ea-820f-9cee5135bc22.png)

Vrátil bych to zpět, popř. testovat, kolik bude řádek, a dělat ten line break jen v případě, že to vyjde na dvě řádky.

**Comment by mkouba** [comment]
> popř. testovat, kolik bude řádek, a dělat ten line break jen v případě, že to vyjde na dvě řádky.

To bohuzel nevim, jak udelat.

**Comment by raguklemenso** [comment]
V pohodě, tak jenom zrušit line break
