### ISSUE TITLE
EN - articles and conjunction in location object listing and inventory listing

### ISSUE THREAD

**Issue by raguklemenso** [primitivedesigns/remakes89#98]
Pří výpisu lokace by se mělo psát "You see a tail" místo "You see tail." Pokud je více předmětů, je třeba změnit spojku a -> and.
Totéž při výpisu inventáře.
Ten neurčitý člen je "a", resp. "an" v případě axe, altar a ID card. Dá se to asi řešit buď výčtem nebo nějakou proměnnou, která určuje, jaký je člen pro daný objekt.

**Comment by mkouba** [comment]
Opraveno.
